# Copyright(c) 2011-2024 The Maintainers of Nanvix.
# Licensed under the MIT License.

name: "Nanvix CI/CD (Self-Hosted)"

concurrency:
  group: self-hosted
  cancel-in-progress: false

on:
  push:
    branches:
      - 'enhancement-*'
      - 'feature-*'
      - 'bugfix-*'
      - 'dev'

env:
  TARGET_BRANCH: ${{ github.ref_name }}

jobs:
  ci:
    name: "Nanvix CI/CD (self-hosted)"
    runs-on: self-hosted
    timeout-minutes: 240
    steps:
    - uses: actions/checkout@v4

    # Rebuild release with logs disabled.
    - name: "Build (release)"
      uses: ./.github/actions/build
      with:
        release: 'release'
        log-level: 'panic'
    - name: "Benchmark (release)"
      uses: ./.github/actions/benchmark
